FROM rust:1-slim-bookworm

WORKDIR /usr/src/app

# Install development dependencies
RUN apt-get update && apt-get install -y pkg-config libssl-dev && rm -rf /var/lib/apt/lists/*

# Install cargo-watch for hot reloading
RUN cargo install cargo-watch

# We don't copy source here because we will bind-mount it in docker-compose
# Just expose the port
ENV PORT=3030
EXPOSE 3030

CMD ["cargo", "watch", "-x", "run"]
